data:
  H: 1080
  W: 1920
  num_keypoints: 24


heatmap:
  sigma: 2
  H: 400
  W: 400


model:
  nstack : 6
  in_dim : 64
  out_dim: 24
  increase: 0
  depth: 3

train:
  accumulate: 1
  batch_size: 1
  betas: [0.5, 0.9]
  checkpoint_dir: 'checkpoints'
  epochs: 1500
  fast_dev_run: False
  gpus: 1
  lr: 0.001
  log_dir: 'logs'
  name: 'test'
  optim: 'adam'
  parallel_calls: 32
  resume: ''
  sample: False
  save_top_k: 3
  steps: 100
  trace: False
  valid_split: 3600
  version: 0
  num_workers : 15

inference:
  length: 1
  path: ''
  save_path: 'samples'
  checkpoint_path: 'outputs/2021-02-17/19-46-48/checkpoints/epoch=25-step=23399.ckpt'