data:
  H: 1080
  W: 1920
  num_keypoints: 24


heatmap:
  sigma: 4
  H: 136
  W: 240


model:
  nstack : 4
  in_dim : 32
  out_dim: 24
  increase: 0
  depth: 3

train:
  accumulate: 1
  batch_size: 4
  betas: [0.5, 0.9]
  checkpoint_dir: 'checkpoints'
  epochs: 1500
  fast_dev_run: False
  gpus: 1
  lr: 0.001
  log_dir: 'logs'
  name: 'test'
  optim: 'adam'
  parallel_calls: 32
  resume: ''
  sample: False
  save_top_k: 3
  steps: 100
  trace: False
  valid_split: 3600
  version: 0
  nun_workers : 5

inference:
  length: 1
  path: ''
  save_path: 'samples'
